// OBD CREATE CAMPIAGN 

export const OBD_CAMPAIGN_NAME= 'campaign_Name'
export const OBD_CAMPAIGN_DESCRIPTION= 'description'
export const OBD_CAMPAIGN_TYPE ='campaign_Type'
export const OBD_DNI='dni'
export const FROM_DATE='from_Date'
export const TO_DATE= 'to_Date'
export const FROM_TIME='from_Time'
export const TO_TIME='to_Time'
export const DIAL_TIMEOUT='dial_Timeout'
export const RETRY_INTERVAL_TYPE='retry_Interval_Type'
export const RETRY_INTERVAL_VALUE='retry_Interval_Value'
export const RETRY_COUNT = 'retry_Count'
export const API_REQUEST = 'api_Req'
export const PING_BACK_URL='pingback_URL'
export const WELCOME_PROMPT='welcome_Prompt'
export const DTMF_REQUEST  ='dtmf_Req'
export const DTMF_LENGTH  = 'dtmf_Length'
export const DTMF_RETRY ='dtmf_Retry'
export const RETRY_LIMIT_EXCEEDED_PROMPT ='retry_Limit_Exceeded_Prompt'
export const THANKS_PROMPT  ='thanks_Prompt'
export const OBD_FILE='file'
export const OBD_CAMPAIGN_ID= 'campaign_ID'
export const STATUS='status'
export const ADMIN_USERNAME = 'ONWEB'
export const ADMIN_PASSWORD='Admin@123'

